apiVersion: v1
kind: PersistentVolume
metadata:
  name: duely-pv-0
spec:
  storageClassName: ""
  capacity:
    storage: 30G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: duely-disk-finland-0
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: duely-pv-0-claim
spec:
  # It's necessary to specify "" as the storageClassName
  # so that the default storage class won't be used, see
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  storageClassName: ""
  volumeName: duely-pv-0
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30G
