apiVersion: v1
kind: Service
metadata:
  name: duely-ui-agency-service
spec:
  type: NodePort
  selector:
    app: duely-ui-agency
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duely-ui-agency-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duely-ui-agency
  template:
    metadata:
      labels:
        app: duely-ui-agency
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: duely-ui-agency
        image: uoleevi/duely-ui-agency:v0.5.1
        resources:
          requests:
            memory: 32Mi
            cpu: 20m
        ports:
        - containerPort: 30
