apiVersion: v1
kind: Service
metadata:
  name: duely-postgres-replica-service
  labels:
    app: duely-postgres-replica
spec:
  selector:
    app: duely-postgres-replica
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: duely-postgres-replica-statefulset
spec:
  selector:
    matchLabels:
      app: duely-postgres-replica
  serviceName: duely-postgres-replica-service
  replicas: 1
  template:
    metadata:
      labels:
        app: duely-postgres-replica
    spec:
      volumes:
        - name: duely-postgres-configmap
          configMap:
            name: duely-postgres-configmap
        - name: duely-postgres-volume
          persistentVolumeClaim:
            claimName: duely-pv-1-claim
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: postgres-replica-setup
          image: postgres:13
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: duely-postgres-secret
                  key: replication-password
          command:
          - sh
          - -c
          - |
            if [ -z "$(ls -A /var/lib/postgresql/data/pgdata)" ]; then
                echo "Running pg_basebackup to catch up replication server...";
                pg_basebackup -R -h duely-postgres-master-service -D /var/lib/postgresql/data/pgdata -P -U replication; 
                chown -R postgres:postgres $PGDATA;
            else
                echo "Skipping pg_basebackup because directory is not empty"; 
            fi
          volumeMounts:
            - name: duely-postgres-volume
              subPath: pgdata
              mountPath: /var/lib/postgresql/data/pgdata
      containers:
        - name: postgres-replica
          image: postgres:13
          resources:
            requests:
              memory: 128Mi
              cpu: 40m
          args: ['-c', 'config_file=/etc/postgres.conf']
          ports:
            - protocol: TCP
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: PGUSER
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: duely-postgres-secret
                  key: postgres-password
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready --host $POD_IP
            failureThreshold: 6
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready --host $POD_IP
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          volumeMounts:
            - name: duely-postgres-volume
              subPath: pgdata
              mountPath: /var/lib/postgresql/data/pgdata
            - name: duely-postgres-configmap
              subPath: postgres.conf
              mountPath: /etc/postgres.conf
            - name: duely-postgres-configmap
              subPath: replica.conf
              mountPath: /etc/replica.conf
