apiVersion: v1
kind: Service
metadata:
  name: duely-postgres-master-service
  labels:
    app: duely-postgres-master
spec:
  selector:
    app: duely-postgres-master
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: duely-postgres-master-statefulset
spec:
  selector:
    matchLabels:
      app: duely-postgres-master
  serviceName: duely-postgres-master-service
  replicas: 1
  template:
    metadata:
      labels:
        app: duely-postgres-master
    spec:
      volumes:
        - name: duely-postgres-configmap
          configMap:
            name: duely-postgres-configmap
        - name: duely-postgres-volume
          persistentVolumeClaim:
            claimName: duely-pv-0-claim
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres-master
          image: postgres:13
          resources:
            requests:
              memory: 128Mi
              cpu: 40m
          args: ['-c', 'config_file=/etc/postgres.conf', '-c', 'hba_file=/etc/pg_hba.conf']
          ports:
            - protocol: TCP
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: PGUSER
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: duely-postgres-secret
                  key: postgres-password
            - name: REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: duely-postgres-secret
                  key: replication-password
            - name: DUELY_SERVICE_ACCOUNT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: duely-postgres-secret
                  key: duely-serviceaccount-password
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready --host $POD_IP
            failureThreshold: 6
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready --host $POD_IP
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          volumeMounts:
            - name: duely-postgres-volume
              subPath: pgdata
              mountPath: /var/lib/postgresql/data/pgdata
            - name: duely-postgres-configmap
              subPath: postgres.conf
              mountPath: /etc/postgres.conf
            - name: duely-postgres-configmap
              subPath: master.conf
              mountPath: /etc/master.conf
            - name: duely-postgres-configmap
              subPath: pg_hba.conf
              mountPath: /etc/pg_hba.conf
            - name: duely-postgres-configmap
              subPath: create-replication-user.sh
              mountPath: /docker-entrypoint-initdb.d/create-replication-user.sh
