apiVersion: v1
kind: Service
metadata:
  name: duely-graphql-service
spec:
  type: NodePort
  selector:
    app: duely-graphql
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duely-graphql-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: duely-graphql
  template:
    metadata:
      labels:
        app: duely-graphql
    spec:
      terminationGracePeriodSeconds: 30
      volumes:
      - name: duely-graphql-secret
        secret:
          secretName: duely-graphql-secret
      containers:
      - name: duely-graphql
        image: uoleevi/duely-graphql:v0.99.0
        resources:
          requests:
            memory: 64Mi
            cpu: 20m
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PGUSER
          value: duely
        - name: PGDATABASE
          value: duely
        - name: PGPASSWORD
          value: duely
        - name: PGHOST
          value: duely-postgres-master-service
        - name: PGPORT
          value: "5432"
        - name: GSERVICEACCOUNTFILE
          value: /usr/src/app/gserviceaccount.json
        - name: STRIPE_PK_TEST
          valueFrom:
            secretKeyRef:
              name: duely-graphql-secret
              key: stripe-pk_test
        - name: STRIPE_SK_TEST
          valueFrom:
            secretKeyRef:
              name: duely-graphql-secret
              key: stripe-sk_test
        - name: STRIPE_PK_LIVE
          valueFrom:
            secretKeyRef:
              name: duely-graphql-secret
              key: stripe-pk_live
        - name: STRIPE_SK_LIVE
          valueFrom:
            secretKeyRef:
              name: duely-graphql-secret
              key: stripe-sk_live
        livenessProbe:
          httpGet:
            path: /.well-known/apollo/server-health
            port: 8080
          failureThreshold: 6
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /.well-known/apollo/server-health
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        volumeMounts:
        - name: duely-graphql-secret
          subPath: gserviceaccount.json
          mountPath: /usr/src/app/gserviceaccount.json
