version: '3'
services:
  api:
    # Uncomment the next line to use a non-root user for all processes.
    # See https://aka.ms/vscode-remote/containers/non-root for details.
    # user: node

    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # Update VARIANT to pick a node version: 10, 12, 14
        VARIANT: 14
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    # Use "ports" to publish your api port locally. Consider "forwardPorts" in
    # devcontainer.json instead if your app only allows connections from localhost. 
    # ports:
    #   - 8080:8080

    volumes:
      - ..:/workspace:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
