### Following comments describe how to use nginx ingress-controller

## 1. If you're using GKE you need to initialize your user as a cluster-admin with the following command:
# kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user $(gcloud config get-value account)

## 2. The following Mandatory Command is required for all deployments.
## For original use:
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml
## For custom use:
# kubectl apply -f ingress-nginx-mandatory.yaml

## 3. Provider Specific Steps: GCE-GKE
## For dynamic ephemeral ip address use:
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/cloud-generic.yaml
## For static ip address use:
# kubectl apply -f ingress-nginx-cloud-static-ip.yaml

## 4. To check if the ingress controller pods have started, run the following command:
# kubectl get pods --all-namespaces -l app.kubernetes.io/name=ingress-nginx --watch

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: duely-ingress-rules
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "999999"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "999999"
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
spec:
  tls:
  - hosts:
    - duely.app
    - '*.duely.app'
    secretName: duely-secret-tls
  rules:
  - host: 'duely.app'
    http:
      paths:
      - path: /asset
        pathType: Prefix
        backend:
          service:
            name: duely-asset-service
            port:
              number: 8080
      - path: /webhook
        pathType: Prefix
        backend:
          service:
            name: duely-webhook-service
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: duely-ui-home-service
            port:
              number: 8080
  - host: 'api.duely.app'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: duely-graphql-service
            port:
              number: 8080
  - host: '*.duely.app'
    http:
      paths:
      - path: /asset
        pathType: Prefix
        backend:
          service:
            name: duely-asset-service
            port:
              number: 8080
      - path: /checkout
        pathType: Prefix
        backend:
          service:
            name: duely-checkout-service
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: duely-ui-agency-service
            port:
              number: 8080
