apiVersion: v1
kind: Service
metadata:
  name: duely-checkout-service
spec:
  type: NodePort
  selector:
    app: duely-checkout
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duely-checkout-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: duely-checkout
  template:
    metadata:
      labels:
        app: duely-checkout
    spec:
      terminationGracePeriodSeconds: 30
      volumes:
      - name: duely-checkout-secret
        secret:
          secretName: duely-checkout-secret
      containers:
      - name: duely-checkout
        image: uoleevi/duely-checkout:v0.3.1
        resources:
          requests:
            memory: 64Mi
            cpu: 20m
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PGUSER
          value: duely
        - name: PGDATABASE
          value: duely
        - name: PGPASSWORD
          value: duely
        - name: PGHOST
          value: duely-postgres-master-service
        - name: PGPORT
          value: "5432"
        - name: DUELY_SERVICE_ACCOUNT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duely-checkout-secret
              key: duely-serviceaccount-password
        livenessProbe:
          httpGet:
            path: /.well-known/server-health
            port: 8080
          failureThreshold: 6
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /.well-known/server-health
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
