version: '3'
services:
  web:
    # Uncomment the next line to use a non-root user for all processes.
    # See https://aka.ms/vscode-remote/containers/non-root for details.
    # user: node

    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update VARIANT to pick a node version: 10, 12, 14
        VARIANT: 14
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    # Use "ports" to publish your web port locally. Consider "forwardPorts" in
    # devcontainer.json instead if your app only allows connections from localhost. 
    # ports:
    #   - 3000:3000

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    links:
      - duely-postgres

    environment:
      PORT: 8080
      PGPORT: 5432
      PGHOST: duely-postgres
      PGUSER: duely
      PGDATABASE: duely
      PGPASSFILE: /workspace/duely-secret/.pgpass
      GSERVICEACCOUNTFILE: /workspace/duely-secret/duely-gserviceaccount.json

  # Note: The PostgreSQL host name is "duely-postgres", not "localhost"
  duely-postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: LocalPassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    
    # Uncomment to allow access to PostgreSQL from external tools
    # ports:
    #  - 5432:5432
