apiVersion: v1
kind: Service
metadata:
  name: duely-x-service
spec:
  type: NodePort
  selector:
    app: duely-x
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duely-x-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duely-x
  template:
    metadata:
      labels:
        app: duely-x
    spec:
      terminationGracePeriodSeconds: 30
      volumes:
      - name: duely-x-secret
        secret:
          secretName: duely-x-secret
      - name: duely-x-volume
        persistentVolumeClaim:
          claimName: duely-pv-2-claim
      containers:
      - name: duely-x
        image: uoleevi/duely-x:v0.1.6
        resources:
          requests:
            memory: 64Mi
            cpu: 20m
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: http://localhost:8080/
        - name: DUELY_X_SERVICES_ASSEMBLY_DIR
          value: /app/data/services
        - name: PGUSER
          value: duely
        - name: PGDATABASE
          value: duely
        - name: PGPASSWORD
          value: duely
        - name: PGHOST
          value: duely-postgres-master-service
        - name: PGPORT
          value: "5432"
        - name: DUELY_SERVICE_ACCOUNT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duely-x-secret
              key: duely-serviceaccount-password
        livenessProbe:
          httpGet:
            path: /.well-known/server-health
            port: 8080
          failureThreshold: 6
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /.well-known/server-health
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        volumeMounts:
          - name: duely-x-volume
            subPath: data
            mountPath: /app/data
