apiVersion: v1
kind: Service
metadata:
  name: duely-ui-home-service
spec:
  type: NodePort
  selector:
    app: duely-ui-home
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duely-ui-home-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duely-ui-home
  template:
    metadata:
      labels:
        app: duely-ui-home
    spec:
      terminationGracePeriodSeconds: 30
      volumes:
        - name: duely-ui-home-secret
          secret:
            secretName: duely-ui-home-secret
      containers:
      - name: duely-ui-home
        image: uoleevi/duely-ui-home:v0.1.0
        resources:
          requests:
            memory: 32Mi
            cpu: 20m
        ports:
        - containerPort: 80
        env:
        - name: DUELY_SERVICE_ACCOUNT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duely-ui-home-secret
              key: duely-serviceaccount-password
