name: duely-cluster-apply

on:
  push:
    branches: [master]

jobs:
  check-image:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.detect-cluster-change.outputs.files }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - id: detect-cluster-change
        run: git diff --name-only ${{ github.sha }}^ ${{ github.sha }} -- './duely-cluster/*.yaml' | sed -e 's/^/ -f .\//' | paste -sd '' | xargs -I{} echo '::set-output name=files::{}'
  update:
    needs: [check-cluster-change]
    if: needs.check-cluster-change.outputs.files != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: duely-project
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud container clusters get-credentials duely-cluster
      - run: kubectl apply ${{ needs.check-cluster-change.outputs.files }}
