name: duely-ui-gke

on:
  push:
    branches: [master]

jobs:
  check-image:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.detect-image-change.outputs.image }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - id: detect-image-change
        run: git diff -U0 -G'image: uoleevi/duely-ui:' ${{ github.sha }}^ ${{ github.sha }} ./duely-cluster/duely-ui/duely-ui.yaml | sed -rn 's/^.*\+\s+image:\s+(uoleevi\/duely-ui:.*)\W*"(.+)".*/::set-output name=image::\1/p'
  update:
    needs: [check-image]
    if: needs.check-image.outputs.image != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: duely-project
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud container clusters get-credentials duely-cluster
      - run: kubectl apply -f .\duely-cluster\duely-ui\duely-ui.yaml
